In [28]:
lst = [ 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x10, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xe0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x01, 0x00, 0x00 ]


In [29]:
import ctypes

In [30]:
aint = []
for i in range(0, len(lst), 4):
    aint.append(lst[i] + (lst[i+1] << 8) + (lst[i+2] << 16) + (lst[i+3] << 24))

In [7]:
print(len(aint) / 7)

16.0


In [30]:
import numpy as np

In [32]:
pint = [ -0x100000000 + i if i & 0x80000000 else i for i in aint]
arr = np.array(pint)

In [33]:
arr.reshape(8, 4)

array([[  0,   2,  14, 256],
       [  0,   2,   5, 256],
       [  0,   2,   1, 256],
       [  0,   4,   2, 272],
       [  0,   4,   0, 224],
       [  0,   4,   0, 272],
       [  0,   4,   0, 288],
       [  0,   4,   0, 304]])

In [22]:
arr

array([-16, -13, -10,  -8,  -5,  -2,   0,   2,   5,   7,   9,  11,  14,
        18])

In [77]:
 channel_div_table = [0 for i in range(0, 21)]
 channel_cnt_table = [0 for i in range(0, 21)]
 channel_cnt_range = [0 for i in range(0,3)]
 rx_notch_para = [[0,0] for i in range(0, 14)]

In [78]:
def get_array(freq):
    global channel_div_table, channel_cnt_table, channel_cnt_range, rx_notch_para, fcal_div
    channel_div_table = [hex(i) for i in channel_div_table]
    channel_cnt_table = [hex(i) for i in channel_cnt_table]
    channel_cnt_range = [hex(i) for i in channel_cnt_range]
    rx_notch_para1 = ["{" + f"{str(i[0])}, {str(i[1])}" + "}" for i in rx_notch_para]
    print(f"static uint32_t channel_div_table_{freq}[21] = "+ "{")
    print("    " + ", ".join(channel_div_table))
    print("};")
    
    print(f"static uint16_t channel_cnt_table_{freq}[21] = " + "{")
    print("    " + ", ".join(channel_cnt_table))
    print("};")

    print(f"static uint16_t channel_cnt_range_{freq}[21] = " + "{")
    print("    " + ", ".join(channel_cnt_range))
    print("};")
    
    print(f"static int32_t rx_notch_para_{freq}[14][2] = "+ "{")
    print("    " + ", ".join(rx_notch_para1))
    print("};")

    print(f"static uint16_t fcal_div_{freq} = {fcal_div};")

In [87]:

        channel_div_table[0] =  0xF690690;
        channel_div_table[1] =  0xF6F96F9;
        channel_div_table[2] =  0xF762762;
        channel_div_table[3] =  0xF7CB7CB;
        channel_div_table[4] =  0xF834835;
        channel_div_table[5] =  0xF89D89E;
        channel_div_table[6] =  0xF906907;
        channel_div_table[7] =  0xF96F970;
        channel_div_table[8] =  0xF9D89D9;
        channel_div_table[9] =  0xFA41A42;
        channel_div_table[10] = 0xFAAAAAB;
        channel_div_table[11] = 0xFB13B14;
        channel_div_table[12] = 0xFB7CB7D;
        channel_div_table[13] = 0xFBE5BE6;
        channel_div_table[14] = 0xFC4EC4F;
        channel_div_table[15] = 0xFCB7CB8;
        channel_div_table[16] = 0xFD20D21;
        channel_div_table[17] = 0xFD89D8A;
        channel_div_table[18] = 0xFDF2DF3;
        channel_div_table[19] = 0xFE5BE5C;
        channel_div_table[20] = 0xFEC4EC5;
        
        channel_cnt_table[0] =  0xA6ED;
        channel_cnt_table[1] =  0xA734;
        channel_cnt_table[2] =  0xA77B;
        channel_cnt_table[3] =  0xA7C2;
        channel_cnt_table[4] =  0xA809;
        channel_cnt_table[5] =  0xA850;
        channel_cnt_table[6] =  0xA897;
        channel_cnt_table[7] =  0xA8DE;
        channel_cnt_table[8] =  0xA925;
        channel_cnt_table[9] =  0xA96D;
        channel_cnt_table[10] = 0xA9B4;
        channel_cnt_table[11] = 0xA9FB;
        channel_cnt_table[12] = 0xAA42;
        channel_cnt_table[13] = 0xAA89;
        channel_cnt_table[14] = 0xAAD0;
        channel_cnt_table[15] = 0xAB17;
        channel_cnt_table[16] = 0xAB5E;
        channel_cnt_table[17] = 0xABA5;
        channel_cnt_table[18] = 0xABEC;
        channel_cnt_table[19] = 0xAC34;
        channel_cnt_table[20] = 0xAC7B;
        
        channel_cnt_range[0] = 0xA6A2;
        channel_cnt_range[1] = 0xA6E2;
        channel_cnt_range[2] = 0xACE2; 
        
        fcal_div = 0xad5;  
        
        rx_notch_para[0][0] = 0; 
        rx_notch_para[1][0] = 0;
        rx_notch_para[2][0] = 0;
        rx_notch_para[3][0] = 0;
        rx_notch_para[4][0] = 0;
        rx_notch_para[5][0] = 1;
        rx_notch_para[6][0] = 1; 
        rx_notch_para[7][0] = 1; 
        rx_notch_para[8][0] = 1;
        rx_notch_para[9][0] = 0;
        rx_notch_para[10][0] = 0;
        rx_notch_para[11][0] = 0;
        rx_notch_para[12][0] = 0;
        rx_notch_para[13][0] = 0; 
        rx_notch_para[0][1] = 0 *1000*1000; 
        rx_notch_para[1][1] = 0 *1000*1000;
        rx_notch_para[2][1] = 0 *1000*1000;
        rx_notch_para[3][1] = 0 *1000*1000;
        rx_notch_para[4][1] = 0 *1000*1000;
        rx_notch_para[5][1] = 7 *1000*1000;
        rx_notch_para[6][1] = 2 *1000*1000; 
        rx_notch_para[7][1] = -3 *1000*1000; 
        rx_notch_para[8][1] = -8 *1000*1000;
        rx_notch_para[9][1] = 0 *1000*1000;
        rx_notch_para[10][1] = 0 *1000*1000;
        rx_notch_para[11][1] = 0 *1000*1000;
        rx_notch_para[12][1] = 0 *1000*1000;
        rx_notch_para[13][1] = 0 *1000*1000; 

In [88]:
get_array("52M")

static uint32_t channel_div_table_52M[21] = {
    0xf690690, 0xf6f96f9, 0xf762762, 0xf7cb7cb, 0xf834835, 0xf89d89e, 0xf906907, 0xf96f970, 0xf9d89d9, 0xfa41a42, 0xfaaaaab, 0xfb13b14, 0xfb7cb7d, 0xfbe5be6, 0xfc4ec4f, 0xfcb7cb8, 0xfd20d21, 0xfd89d8a, 0xfdf2df3, 0xfe5be5c, 0xfec4ec5
};
static uint16_t channel_cnt_table_52M[21] = {
    0xa6ed, 0xa734, 0xa77b, 0xa7c2, 0xa809, 0xa850, 0xa897, 0xa8de, 0xa925, 0xa96d, 0xa9b4, 0xa9fb, 0xaa42, 0xaa89, 0xaad0, 0xab17, 0xab5e, 0xaba5, 0xabec, 0xac34, 0xac7b
};
static uint16_t channel_cnt_range_52M[21] = {
    0xa6a2, 0xa6e2, 0xace2
};
static int32_t rx_notch_para_52M[14][2] = {
    {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {1, 7000000}, {1, 2000000}, {1, -3000000}, {1, -8000000}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}
};
static uint16_t fcal_div_52M = 2773;


In [2]:
 s = """00000000 01000000 07000000 1b000000  
 20000000 fcffffff e6000000 00000000 
 01000000 07000000 1b000000 20000000 
 f8ffffff dc000000 00000000 01000000 
 07000000 14000000 20000000 fcffffff 
 d2000000 00000000 01000000 07000000 
 14000000 20000000 f8ffffff c8000000 
 00000000 01000000 07000000 0f000000 
 20000000 fcffffff be000000 00000000 
 01000000 07000000 0f000000 20000000 
 f8ffffff b4000000 00000000 01000000 
 07000000 0b000000 20000000 fcffffff 
 aa000000 00000000 01000000 07000000 
 0b000000 20000000 f8ffffff a0000000 
 00000000 01000000 06000000 0a000000 
 20000000 fcffffff 96000000 00000000 
 01000000 06000000 0a000000 20000000 
 f8ffffff 8c000000 00000000 01000000 
 06000000 08000000 20000000 fbffffff 
 82000000 00000000 01000000 06000000 
 08000000 20000000 f7ffffff 78000000 
 00000000 01000000 05000000 07000000 
 20000000 fcffffff 6e000000 00000000 
 01000000 05000000 07000000 20000000 
 f8ffffff 64000000 00000000 01000000 
 04000000 07000000 20000000 fbffffff 
 5a000000 00000000 01000000 04000000 
 07000000 20000000 f7ffffff 50000000"""

In [9]:
ints = s.replace("\n", "").replace("  ", " ").split(" ")

In [33]:
data = [int.from_bytes(bytearray.fromhex(i), byteorder='little') for i in ints]
data = [ -0x100000000 + i if i & 0x80000000 else i for i in data]

In [34]:
na = np.array(data)
na.reshape(16,7)

array([[  0,   1,   7,  27,  32,  -4, 230],
       [  0,   1,   7,  27,  32,  -8, 220],
       [  0,   1,   7,  20,  32,  -4, 210],
       [  0,   1,   7,  20,  32,  -8, 200],
       [  0,   1,   7,  15,  32,  -4, 190],
       [  0,   1,   7,  15,  32,  -8, 180],
       [  0,   1,   7,  11,  32,  -4, 170],
       [  0,   1,   7,  11,  32,  -8, 160],
       [  0,   1,   6,  10,  32,  -4, 150],
       [  0,   1,   6,  10,  32,  -8, 140],
       [  0,   1,   6,   8,  32,  -5, 130],
       [  0,   1,   6,   8,  32,  -9, 120],
       [  0,   1,   5,   7,  32,  -4, 110],
       [  0,   1,   5,   7,  32,  -8, 100],
       [  0,   1,   4,   7,  32,  -5,  90],
       [  0,   1,   4,   7,  32,  -9,  80]])